#!/usr/bin/env bash
# Setup script for PredArb on a Proxmox LXC container.
# Tested on Debian 12 (bookworm) and Debian 13 (trixie) LXCs.
#
# Usage: bash deploy/setup-lxc.sh
#
# Prerequisites: LXC with nesting enabled (for Docker).
#   In Proxmox: Options → Features → check "Nesting"

set -euo pipefail

INSTALL_DIR="/opt/predarb"
REPO_URL="${PREDARB_REPO_URL:-}"  # Set if cloning from git

echo "=== PredArb LXC Setup ==="

# 1. Install Docker (if not present)
if ! command -v docker &>/dev/null; then
    echo "Installing Docker..."
    apt-get update
    apt-get install -y ca-certificates curl gnupg
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg

    # Detect Debian codename (bookworm, trixie, etc.)
    CODENAME=$(. /etc/os-release && echo "$VERSION_CODENAME")
    # Trixie (Debian 13) may not have a Docker repo yet — fall back to bookworm
    if ! curl -sf "https://download.docker.com/linux/debian/dists/${CODENAME}/Release" >/dev/null 2>&1; then
        echo "No Docker repo for ${CODENAME}, falling back to bookworm"
        CODENAME="bookworm"
    fi

    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
      https://download.docker.com/linux/debian ${CODENAME} stable" \
      > /etc/apt/sources.list.d/docker.list
    apt-get update
    apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
    systemctl enable docker
fi

# 2. Create install directory
mkdir -p "$INSTALL_DIR"

# 3. Clone or copy repo
if [ -n "$REPO_URL" ]; then
    apt-get install -y git
    git clone "$REPO_URL" "$INSTALL_DIR"
elif [ -d "/tmp/predarb-src" ]; then
    cp -r /tmp/predarb-src/* "$INSTALL_DIR/"
else
    echo "Copy the PredArb source to $INSTALL_DIR before continuing."
    echo "  e.g.: rsync -av ./PredictionArbitrage/ root@<lxc-ip>:$INSTALL_DIR/"
    exit 1
fi

cd "$INSTALL_DIR"

# 4. Create .env if missing
if [ ! -f .env ]; then
    echo "Creating .env from template..."
    DB_PASSWORD=$(openssl rand -base64 24 | tr -d '=/+')
    cat > .env <<EOF
# Generated by setup-lxc.sh
DATABASE_URL=postgresql+asyncpg://predarb:${DB_PASSWORD}@postgres:5432/predarb
REDIS_URL=redis://redis:6379/0
DB_PASSWORD=${DB_PASSWORD}

# Discord Webhook — fill this in
DISCORD_WEBHOOK_URL=

# App Config
POLL_INTERVAL_SECONDS=60
MIN_PROFIT_PCT=1.0
MIN_LIQUIDITY_USD=50.0
LOG_LEVEL=INFO
EOF
    echo ".env created with random DB password."
    echo "Edit $INSTALL_DIR/.env to add your Discord webhook URLs."
fi

# 5. Install systemd service
cp deploy/predarb.service /etc/systemd/system/predarb.service
systemctl daemon-reload
systemctl enable predarb

# 6. Build and start
echo "Building containers (this may take a few minutes)..."
docker compose build
docker compose up -d

echo ""
echo "=== PredArb is running! ==="
echo "  Dashboard:  http://localhost:8420"
echo "  Health API: http://localhost:8420/api/v1/health"
echo ""
echo "If using Tailscale, access via: http://$(hostname).tail-net:8420"
echo ""
echo "Next steps:"
echo "  1. Edit $INSTALL_DIR/.env to add DISCORD_WEBHOOK_* URLs"
echo "  2. Restart: docker compose restart predarb"
echo "  3. Logs:    docker compose logs -f predarb"
